mobile portfolio skeleton design
MishDM/misikir-portfolio pull request #3
Opened 2022-07-01 19:52 UTC by MishDM

add portfolio images
add portfolio styles
add portfolio information

2022-07-01 22:30 UTC, HAMMAS-SALEEM requested changes
# Changes Requested :recycle:

![almost there](https://media.makeameme.org/created/almost-there-finish.jpg)

## Hey @MishDM :wave:
### Highlights :1st_place_medal:

Your project is working :clap:
Good commit history :heavy_check_mark:
Following Github Flow :heavy_check_mark:
Following HTML, CSS best practices :heavy_check_mark:
Following Figma template :art:
Using .gitignore file :heavy_check_mark:
Meaningful commit messages :heavy_check_mark:
Descriptive PR title :heavy_check_mark:
Descriptive PR Summary :+1:
Linters are green :green_circle:

You have made a great effort on your project :blush: and I can see that but you need to work on some issues to go to the next project but you are almost there. :+1:

### **_Any requested change with the optional tag is not crucial enough to prevent you from getting approval. But we, highly recommend that you to take these changes into consideration_**

### Once you implement all the changes you should be ready to submit your project for a re-review :rocket: :rocket:

Cheers and Happy coding!👏👏👏

### Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. You can reach out to me on slack by searching my name (Hammas Bin Saleem) for any explanation.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 22:30 UTC, HAMMAS-SALEEM commented on css/style.css
> +  background-size: cover;
### Your Project on Production :bust_in_silhouette:
![no-background-production (copy)](https://user-images.githubusercontent.com/93039359/176972974-12e916f5-c23b-4e33-8302-9e596e40d1de.png)


- [ ] Your background image is visible on the local server. :+1: But when I tried your application on the production site then there your background image was not visible. The problem is with your **URL**. Please fix the issue as I fixed it in the image below :arrow_down:

### Your Project on Local Machine
![background-size-issue (copy)](https://user-images.githubusercontent.com/93039359/176972951-8c5b645a-1ed3-437a-bbe9-f1c81c91e2a7.png)

- [ ] Your background is going out of resolution. Please fix the background-size: 100%; as suggested in the image below. :arrow_down_small:

### My fIx for both issues :point_down:
![background-fix (copy)](https://user-images.githubusercontent.com/93039359/176973153-0e57f8d2-be96-4467-8a8b-3302e9022c6b.png)

2022-07-01 22:30 UTC, HAMMAS-SALEEM commented on index.html
> +    </h1>
# Your Heading
![Screenshot from 2022-07-02 03-17-41](https://user-images.githubusercontent.com/93039359/176973608-dd62d509-dd9d-4ef0-a6bd-11e163d85106.png)


# Figma Heading
![heading-figma](https://user-images.githubusercontent.com/93039359/176973506-a96eb11d-cda6-4ab4-ab9c-a2365bc4f4e3.png)

- [ ] Please compare your heading with the Figma heading. Please make your heading as bold as in the Figma template. :+1:
- [ ] Please add `margin-bottom: 12px;` to your heading. :blush:

2022-07-02 14:12 UTC, mmsesay reviewed
Hi @MishDM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has falling linters.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-02 14:35 UTC, merged

2022-07-02 14:39 UTC, mmsesay reviewed
Hi @MishDM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has been merged without approval.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._